### ISSUE TITLE
release it as a binary on github

### ISSUE THREAD

**Issue by m040601** [FreeMasen/mdbook-presentation-preprocessor#3]
This is such a great addon to the (great) mdbook.
Thank you for your work.
Would it be possible to release it as a binary ? At least compiled for x86_64.
It would make it much easier to release this as a precompiled package for arch linux and other distros. It would make much easier for people who dont have the entire rust distribution to quickly try it out.

**Comment by FreeMasen** [comment]
Thanks!

I could probably arrange that.

**Comment by FreeMasen** [comment]
I've added the Linux and MacOS binaries, I should be able to add a windows binary this week.

**Comment by FreeMasen** [comment]
I have now uploaded 3 x86_64 binaries (one for MacOS, one for Linux, and one for Windows). You can find them [here](https://github.com/FreeMasen/mdbook-presentation-preprocessor/releases/tag/v0.2.0).

I am working on getting them automatically built by CI but for now I am going to close this issue. Feel free to re-open it or create a new one if you run into any problems with the release.
